name: Build and deploy ASP.Net Core app to Azure Web App - tropinailspro

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Configurar .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Compilar la aplicación
        run: dotnet build --configuration Release

      - name: Publicar con dotnet
        run: dotnet publish -c Release -o "${{ github.workspace }}/myapp"

      - name: Subir artefactos para despliegue
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{ github.workspace }}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Descargar artefactos
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login a Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Desplegar a Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'tropinailspro'
          slot-name: 'Production'
          package: ${{ github.workspace }}/myapp
